setup-deps: switch to pfds fork to include bug fixes
Among other things, this fixes a crash discovered when trying to show
a hash-map with three items (hamts fold definition was broken in one
case).

Signed-off-by: Rob Browning <rlb@defaultvalue.org>

diff --git a/setup-deps b/setup-deps
--- a/setup-deps
+++ b/setup-deps
@@ -2,6 +2,10 @@
 
 set -xe
 
+pfds_src='https://github.com/rlbdv/pfds.git'
+pfds_ref=tmp/exp
+pfds_hash=1fa268b36e8c61d6349c3ce542cbd691cc42f9de
+
 # For now we don't attempt updates
 if test -d mod/pfds; then
     echo error: pfds directory already exists 1>&2
@@ -11,11 +15,12 @@ fi
 tmpdir="$(mktemp -d "tmp-pfds-XXXXXXX")"
 trap "$(printf "rm -rf %q" "$tmpdir")" EXIT
 
-git clone -b v0.3 https://github.com/ijp/pfds.git "$tmpdir/pfds"
+git clone -n "$pfds_src" "$tmpdir/pfds"
+git -C "$tmpdir/pfds" checkout "$pfds_ref"
 
-actual_hash="$(git -C "$tmpdir/pfds" rev-parse v0.3^{})"
-if test "$actual_hash" != 454033f82dac7c0b0ea9e84eed1e8ed316487c78; then
-    echo "ERROR: cloned unexpected pfds v0.3 hash $actual_hash" 1>&2
+actual_hash="$(git -C "$tmpdir/pfds" rev-parse "$pfds_ref^{}")"
+if test "$actual_hash" != "$pfds_hash"; then
+    echo "error: clone of $pfds_ref has unexpected hash $pfds_hash" 1>&2
     exit 2
 fi
 
